services:
  db: 
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - "3306:3306"
  phpMyAdmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITARY= 1
    ports:
      - "8080:80"